INSERT OR REPLACE INTO LocalizedText
    (Tag,	Language,	Text)
VALUES
    -- English
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'en_US',	'Enhanced Town Focus Info'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'en_US',	'An enhanced display of town focus yield bonuses in Civ7, showing detailed breakdowns of improvements, buildings, and trade routes that contribute to specialization bonuses.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'en_US',	'Special Quarters'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'en_US',	'Building Quarters'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'en_US',	'Era Bonus'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'en_US',	'Woodcutter'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'en_US',	'Mine'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'en_US',	'Fishing Boat'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'en_US',	'Farm'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'en_US',	'Pasture'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'en_US',	'Plantation'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'en_US',	'Camp'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'en_US',	'Clay Pit'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'en_US',	'Quarry'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'en_US',	'Trade Routes'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'en_US',	'Connected Settlements'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'en_US',	'Cities'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'en_US',	'Towns'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'en_US',	'Bonus per connection'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'en_US',	'Total Resources'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'en_US',	'Happiness per Resource'),
    ('LOC_MOD_ETFI_RESOURCES',	        'en_US',	'Resources'),
    -- Japanese
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'ja_JP',	'Enhanced Town Focus Info (専門化選択時の詳細な生産表示)'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'ja_JP',	'都市の専門化を選択する際に、改善施設、建物、交易路からの詳細なボーナス内訳を表示します。'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'ja_JP',	'特殊区画 (+1 ずつ)'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'ja_JP',	'建物区画 (+1 ずつ)'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'ja_JP',	'時代ボーナス'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'ja_JP',	'木こり小屋'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'ja_JP',	'鉱山'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'ja_JP',	'漁船'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'ja_JP',	'農場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'ja_JP',	'牧場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'ja_JP',	'プランテーション'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'ja_JP',	'狩猟キャンプ'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'ja_JP',	'粘土採掘場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'ja_JP',	'採石場'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'ja_JP',	'交易路'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'ja_JP',	'接続された居住地'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'ja_JP',	'都市'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'ja_JP',	'町'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'ja_JP',	'接続ごとのボーナス'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'ja_JP',	'資源の合計'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'ja_JP',	'資源ごとの幸福度'),
    ('LOC_MOD_ETFI_RESOURCES',	        'ja_JP',	'資源'); 